// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKQfa4ZBvYmNcDRK4geOxOJJ3dwKR0SAs',
    appId: '1:999882574357:web:dd52d94f2ef283d971dc1c',
    messagingSenderId: '999882574357',
    projectId: 'prueba-aplicaciones-fb0e9',
    authDomain: 'prueba-aplicaciones-fb0e9.firebaseapp.com',
    storageBucket: 'prueba-aplicaciones-fb0e9.firebasestorage.app',
    measurementId: 'G-W1RGMBL5T6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHQeK3XKm9AX2T73aX0nX0d9eGb1lmHuI',
    appId: '1:999882574357:android:a7410e979f4137ac71dc1c',
    messagingSenderId: '999882574357',
    projectId: 'prueba-aplicaciones-fb0e9',
    storageBucket: 'prueba-aplicaciones-fb0e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCviMOfMgKLkzALN_iS09sggh8yjlcC2tg',
    appId: '1:999882574357:ios:ab5b1a1b8f74153c71dc1c',
    messagingSenderId: '999882574357',
    projectId: 'prueba-aplicaciones-fb0e9',
    storageBucket: 'prueba-aplicaciones-fb0e9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCviMOfMgKLkzALN_iS09sggh8yjlcC2tg',
    appId: '1:999882574357:ios:ab5b1a1b8f74153c71dc1c',
    messagingSenderId: '999882574357',
    projectId: 'prueba-aplicaciones-fb0e9',
    storageBucket: 'prueba-aplicaciones-fb0e9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKQfa4ZBvYmNcDRK4geOxOJJ3dwKR0SAs',
    appId: '1:999882574357:web:ae135a3fdf0b84a971dc1c',
    messagingSenderId: '999882574357',
    projectId: 'prueba-aplicaciones-fb0e9',
    authDomain: 'prueba-aplicaciones-fb0e9.firebaseapp.com',
    storageBucket: 'prueba-aplicaciones-fb0e9.firebasestorage.app',
    measurementId: 'G-SCKEKMP3GW',
  );
}
